buildstep-ssh: &buildstep-ssh
  image: appleboy/drone-ssh
  pull: true
  host: ianthe.rem.uz
  port: 22
  user: root
  secrets: [ ssh_key ]

buildstep-node: &buildstep-node
  image: webhippie/nodejs:latest
  pull: true

workspace:
  base: /srv/app
clone:
  git:
    image: plugins/git:1
    depth: 1
    tags: false
    submodule_override:
      img: https://git.develop.5eTools.com/5eTools/5etools_img.git

pipeline:
###############################################################################
# All Branches
# Push || Pull request -> Test -> Notify
  Test:
      <<: *buildstep-node
      commands:
          - npm install
          - npm test
      when:
          event: pull_request

  Test:
      <<: *buildstep-node
      commands:
          - npm install
          - npm test
      when:
          event: push
          branch: development

###############################################################################
# Master Branch
# ... -> Merge -> Version Check -> Deploy
  Check-version:
    <<: *buildstep-ssh
    script:
      - cd /scripts/ && python /scripts/chk-version.py
    when:
      branch: master
      event: [ push, pull_request ]

  Update-version:
    <<: *buildstep-ssh
    script:
      - cd /scripts/ && python /scripts/upd-version.py
    when:
      branch: master
      event: push

  Deploy-prod:
    <<: *buildstep-ssh
    command_timeout: 300
    script:
      - bash /scripts/prod-deploy.sh
    when:
      branch: master
      event: push

###############################################################################
# Development Branch
# ... -> Deploy
  Deploy-dev:
    <<: *buildstep-ssh
    command_timeout: 300
    script:
      - bash /scripts/dev-deploy.sh
    when:
      branch: development
      event: push

###############################################################################
# All Branches
# ... -> Notify || Shame

  Shame:
    <<: *buildstep-ssh
    script:
      - python /scripts/shame.py
    when:
       status: failure
       event: [ push, pull_request ]