workspace:
  base: /srv/app
clone:
  git:
    image: plugins/git:1
    depth: 1
    tags: false

pipeline:
###############################################################################
# All Branches
# Push || Pull request -> Test -> Notify || Shame
  Test:
      image: webhippie/nodejs:latest
      pull: true
      commands:
          - npm install
          - npm test
      when:
          event: pull_request

  Test:
      image: webhippie/nodejs:latest
      pull: true
      commands:
          - npm install
          - npm test
      when:
          event: push
          branch: development

  Notify:
      image: appleboy/drone-discord
      pull: true
      secrets: [ discord_webhook_id, discord_webhook_token ]
      message: >
       5etools test of {{ build.number }} to {{ build.branch }} by
       {{ build.author }} finished with {{ build.status }}.
       ({{ build.link }})
      when:
        status: success
        event: [ push, pull_request ]

  Shame:
    image: appleboy/drone-ssh
    pull: true
    host: ianthe.rem.uz
    port: 22
    user: root
    secrets: [ ssh_key ]
    script:
      - python /scripts/shame.py
    when:
       status: failure
       event: [ push, pull_request ]

###############################################################################
# Master Branch
# ... -> Merge -> Version Check -> Deploy
  Version:
    image: appleboy/drone-ssh
    pull: true
    host: ianthe.rem.uz
    port: 22
    user: root
    secrets: [ ssh_key ]
    script:
      - cd /scripts/ && python /scripts/chk-version.py
    when:
      branch: master
      event: push

  Deploy-prod:
    image: appleboy/drone-ssh
    pull: true
    host: ianthe.rem.uz
    port: 22
    user: root
    secrets: [ ssh_key ]
    command_timeout: 180
    script:
      - bash /scripts/prod-deploy.sh
    when:
      branch: master
      event: push

###############################################################################
# Development Branch
# ... -> Deploy
  Deploy-dev:
    image: appleboy/drone-ssh
    pull: true
    host: ianthe.rem.uz
    port: 22
    user: root
    secrets: [ ssh_key ]
    command_timeout: 180
    script:
      - bash /scripts/dev-deploy.sh
    when:
      branch: development
      event: push

###############################################################################
# All Branches
# ... -> Notify
  Notify:
      image: appleboy/drone-discord
      pull: true
      secrets: [ discord_webhook_id, discord_webhook_token ]
      message: >
       5etools deployment of {{ build.number }} from {{ build.branch }} by
       {{ build.author }} finished with {{ build.status }}.
       ({{ build.link }})
      when:
        status:  [ failure, success ]
        event: push